# Generated by Django 5.2.8 on 2025-11-19 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadeddataset',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Uploaded Dataset', 'verbose_name_plural': 'Uploaded Datasets'},
        ),
        migrations.AddField(
            model_name='uploadeddataset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadeddataset',
            name='csv_file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
